#!/usr/bin/env bash
set -eo pipefail
umask 077  # every temp and cache file is born private, no chmod race

# Add or update ONE secret in values.age, then regenerate ~/.local/secrets.
#
# Authenticates to 1Password at most ONCE per login session: the age private key
# is fetched from 1Password on first use and cached in tmpfs (/dev/shm, RAM-backed,
# chmod 600), then reused by later runs in the same session — no repeat prompts.
# The cache is wiped on reboot, when the `claude` shell function exits
# (claude-sudo-clear pattern), or explicitly via secret-session-clear.sh.
#
# This is the supported way to install secret material — never leave loose key
# files on disk. values.age is the source of truth; sync.sh pushes to Workers.
#
# Usage:
#   secret-set.sh NAME --stdin             # prompt for the value, no echo (preferred
#                                          #   interactive form: keeps the value out of
#                                          #   shell history, /proc cmdline, transcripts)
#   secret-set.sh NAME --value 'literal'   # single-line value on the command line
#                                          #   (non-interactive callers only)
#   secret-set.sh NAME --file PATH         # raw file contents (must be single-line)
#   secret-set.sh NAME --b64-file PATH     # base64-encode a file → single line
#                                          #   (use for PEMs / any multi-line material;
#                                          #    decode with atob()/base64 -d at the consumer)
#   secret-set.sh --sync                   # just regenerate ~/.local/secrets, no edit
#   secret-set.sh NAME --delete            # remove NAME from values.age (git keeps history)
#   secret-set.sh --dry-run NAME --value … # show what would change, write nothing
#
# After adding, document the secret in registry.md and (for Workers) add it to the
# routing table in sync.sh, then run sync.sh --worker NAME.

RECIP="age197mcd2m3z90t49n9t5v3ujjntw7krfkw5y9sjfc545v28qvezugshg7jgk"
VALUES="$HOME/.dotfiles/secrets/values.age"
LOCAL_SECRETS="$HOME/.local/secrets"
CACHE="/dev/shm/.age-key-$(id -u)"      # session-cached age key (RAM, chmod 600)
OP_ITEM="Workstation age encryption key"

die() { echo "Error: $*" >&2; exit 1; }

usage() { sed -n '4,35p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

# --- Parse arguments ---
NAME=""
MODE=""
SRC=""
DRY_RUN=false
SYNC_ONLY=false
DELETE=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stdin)    MODE="stdin";    shift ;;
        --value)    MODE="value";    SRC="${2:?--value needs an argument}"; shift 2 ;;
        --file)     MODE="file";     SRC="${2:?--file needs a path}";       shift 2 ;;
        --b64-file) MODE="b64-file"; SRC="${2:?--b64-file needs a path}";   shift 2 ;;
        --sync)     SYNC_ONLY=true;  shift ;;
        --delete)   DELETE=true;     shift ;;
        --dry-run)  DRY_RUN=true;    shift ;;
        -h|--help)  usage 0 ;;
        -*)         die "unknown option: $1" ;;
        *)          [[ -z "$NAME" ]] && NAME="$1" || die "unexpected arg: $1"; shift ;;
    esac
done

# --- Fetch age key once per session, cache in tmpfs ---
ensure_key() {
    if [[ ! -s "$CACHE" ]]; then
        echo "Fetching age key from 1Password (once per session)…" >&2
        op item get "$OP_ITEM" --fields notesPlain --reveal 2>/dev/null \
            | sed 's/^"//;s/"$//' > "$CACHE" || true
        chmod 600 "$CACHE" 2>/dev/null || true
        if [[ ! -s "$CACHE" ]]; then
            rm -f "$CACHE"
            die "could not fetch age key — is the 1Password app unlocked?"
        fi
    fi
}

# --- Write ~/.local/secrets from a decrypted plaintext file (mirrors sync.sh) ---
write_local() {
    local dec="$1"
    local out
    out="$(mktemp /dev/shm/local-secrets-XXXXXX)"
    {
        echo "# Workstation secrets — generated by ~/.dotfiles/scripts/secrets/sync.sh"
        echo "# DO NOT EDIT — re-run sync.sh to update"
        echo ""
        while IFS='=' read -r k v; do
            [[ -z "$k" || "$k" =~ ^# ]] && continue
            echo "export ${k}=${v}"
        done < "$dec"
    } > "$out"
    cp "$out" "$LOCAL_SECRETS"
    chmod 600 "$LOCAL_SECRETS"
    shred -u "$out" 2>/dev/null || rm -f "$out"
}

DEC="$(mktemp /dev/shm/values-dec-XXXXXX)"
NEW="$(mktemp /dev/shm/values-new-XXXXXX)"
trap 'shred -u "$DEC" "$NEW" 2>/dev/null; rm -f "$VALUES.tmp" 2>/dev/null' EXIT

ensure_key
age --decrypt -i "$CACHE" "$VALUES" > "$DEC" || die "decrypt failed (stale cached key? run secret-session-clear.sh)"
chmod 600 "$DEC"

# --- Sync-only: just regenerate local from current values.age ---
if [[ "$SYNC_ONLY" == true ]]; then
    if [[ "$DRY_RUN" == true ]]; then
        echo "[dry-run] would regenerate $LOCAL_SECRETS from values.age"
        exit 0
    fi
    write_local "$DEC"
    echo "Regenerated $LOCAL_SECRETS ($(grep -c '^export ' "$LOCAL_SECRETS") secrets)."
    exit 0
fi

[[ -n "$NAME" ]] || die "missing secret NAME (or use --sync). See --help."
[[ "$NAME" =~ ^[A-Z][A-Z0-9_]*$ ]] || die "NAME must be UPPER_SNAKE_CASE: '$NAME'"
# --- Delete: drop NAME, verify the new ciphertext no longer carries it ---
if [[ "$DELETE" == true ]]; then
    [[ -z "$MODE" ]] || die "--delete takes no value option"
    grep -q "^${NAME}=" "$DEC" || die "$NAME is not in values.age"
    grep -v "^${NAME}=" "$DEC" > "$NEW" || true
    chmod 600 "$NEW"
    if [[ "$DRY_RUN" == true ]]; then
        echo "[dry-run] would delete $NAME from values.age and regenerate $LOCAL_SECRETS"
        exit 0
    fi
    age -r "$RECIP" -o "$VALUES.tmp" "$NEW"
    if ! age --decrypt -i "$CACHE" "$VALUES.tmp" | grep -q "^${NAME}=" \
        && [[ "$(age --decrypt -i "$CACHE" "$VALUES.tmp" | grep -c '=')" -eq "$(grep -c '=' "$NEW")" ]]; then
        mv "$VALUES.tmp" "$VALUES"
    else
        rm -f "$VALUES.tmp"; die "verification failed: values.age left untouched"
    fi
    write_local "$NEW"
    echo "OK: ${NAME} deleted from values.age + ~/.local/secrets. Remember to update registry.md."
    exit 0
fi

[[ -n "$MODE" ]] || die "need one of --stdin / --value / --file / --b64-file (or --sync, --delete)"

# --- Build the value (always single-line) ---
case "$MODE" in
    stdin)    IFS= read -rsp "Value for ${NAME} (no echo): " VAL; echo >&2 ;;
    value)    VAL="$SRC" ;;
    file)     [[ -f "$SRC" ]] || die "no such file: $SRC"; VAL="$(cat "$SRC")" ;;
    b64-file) [[ -f "$SRC" ]] || die "no such file: $SRC"; VAL="$(base64 -w0 "$SRC")" ;;
esac
[[ "$VAL" == *$'\n'* ]] && die "value is multi-line — use --b64-file for PEMs/multi-line material"

# --- Replace any existing line for NAME, append the new one ---
grep -v "^${NAME}=" "$DEC" > "$NEW" || true
[[ -s "$NEW" && -n "$(tail -c1 "$NEW")" ]] && echo >> "$NEW"
printf '%s=%s\n' "$NAME" "$VAL" >> "$NEW"
chmod 600 "$NEW"

if grep -q "^${NAME}=" "$DEC"; then
    EXISTED="updated"
else
    EXISTED="added"
fi
if [[ "$DRY_RUN" == true ]]; then
    echo "[dry-run] would $EXISTED $NAME (${#VAL} chars) in values.age and regenerate $LOCAL_SECRETS"
    exit 0
fi

# --- Re-encrypt, verify the new ciphertext before swapping ---
age -r "$RECIP" -o "$VALUES.tmp" "$NEW"
if age --decrypt -i "$CACHE" "$VALUES.tmp" | grep -q "^${NAME}="; then
    mv "$VALUES.tmp" "$VALUES"
else
    rm -f "$VALUES.tmp"; die "verification failed — values.age left untouched"
fi

write_local "$NEW"
echo "OK: ${NAME} ${EXISTED} in values.age + ~/.local/secrets. Remember to update registry.md."
